# Generated by Django 5.2.17 on 2026-10-02 16:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('health_data_processing', 'Processing of health data'), ('study_matching_contact', 'Contact about matching studies'), ('terms', 'Terms of use')], max_length=40)),
                ('version', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('sk', 'Slovenčina'), ('en', 'English')], default='sk', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('kind', 'version', 'language'), name='unique_consent_doc_version')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='consents.consentdocument')),
            ],
            options={
                'ordering': ('-granted_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True)), fields=('user', 'document'), name='unique_active_consent')],
            },
        ),
    ]
