# Generated by Django 5.2.17 on 2026-10-02 16:35

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='studies.study')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'participant'), name='unique_questionnaire_response')],
            },
        ),
    ]
